NxtLvl/NxtLvl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
    
]

NxtLvl/crm/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name=''),
    path('register', views.register, name='register'),
    path('my-login', views.my_login, name='my-login'), # Same as route name
    path('user-logout', views.user_logout, name='user-logout'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('create-record', views.create_record, name='create-record'),
    path('update-record/<int:pk>', views.update_record, name='update-record'),
    path('record/<int:pk>', views.single_record, name='record'),
    path('delete-record/<int:pk>', views.delete_record, name='delete-record'),
    
]

NxtLvl/crm/models.py
from django.db import models


class ClientRecord(models.Model):
    
    PROGRESS_CHOICES = [
        ('not_started', 'Not Started'),
        ('in_progress', 'In Progress'),
        ('finished', 'Finished'),
    ]
    
    creation_date = models.DateTimeField(auto_now_add=True)
    
    
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=300)
    city = models.CharField(max_length=255)
    country= models.CharField(max_length=125)
    company_name = models.CharField(max_length=300)
    work_info = models.TextField()
    start_date = models.DateTimeField()
    current_status = models.CharField(max_length=20, choices=PROGRESS_CHOICES, default='not_started')
    progress_percentage = models.CharField(max_length=100)
    delivery_date = models.DateTimeField()
    deal_amount = models.FloatField()
    
    def __str__(self):
        
        return self.first_name + '   ' + self.last_name
    
    
    
    

NxtLvl/crm/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput
from .models import ClientRecord


from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.forms.widgets import DateTimeInput

# Create/Register a User

class CreateUserForm(UserCreationForm):
    
    class Meta:
        
        model = User
        fields = ['username', 'password1', 'password2']
        
        

# Login a User

class LoginForm(AuthenticationForm):
    
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())
    
        
# Add a Record 
class AddRecordForm(forms.ModelForm):
    
    class Meta:
        
        model = ClientRecord
        fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'city', 'country', 'company_name', 'work_info', 'start_date', 'current_status', 'progress_percentage', 'delivery_date', 'deal_amount']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'start_date', 'delivery_date',
            Submit('submit', 'save')
        )
        self.fields['start_date'].widget = DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M')
        self.fields['delivery_date'].widget = DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M')
        
        

# Update a Record 
class UpdateRecordForm(forms.ModelForm):
    
    class Meta:
        
        model = ClientRecord
        fields = ['first_name', 'last_name', 'email', 'phone', 'address', 'city', 'country', 'company_name', 'work_info', 'start_date', 'current_status', 'progress_percentage', 'delivery_date', 'deal_amount']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'start_date', 'delivery_date',
            Submit('submit', 'save')
        )
        self.fields['start_date'].widget = DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M')
        self.fields['delivery_date'].widget = DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M')

NxtLvl/crm/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm, LoginForm, AddRecordForm, UpdateRecordForm
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from .models import ClientRecord
from django.contrib import messages

# Homepage
def home(request):
    
    return render(request, 'crm/index.html')


# Register
def register(request):
    
    form = CreateUserForm()
    
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created succesfully!')
            
            return redirect('my-login')
    
    context = {'form': form}
    
    return render(request, 'crm/register.html', context=context)


# Login a User
def my_login(request):
    form = LoginForm()
    
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                auth.login(request, user)
                
                
                return redirect('dashboard')
                
    context = {'login_form':form}
    return render(request, 'crm/my-login.html', context=context)


# Logout 
def user_logout(request):
    auth.logout(request)
    messages.success(request, 'Logged out successfully!')
    return redirect('my-login')


# Dashboard
@login_required(login_url='my-login')
def dashboard(request):
    
    my_records = ClientRecord.objects.all()

    context = {'records': my_records}
    
    return render(request, 'crm/dashboard.html', context=context)

# Add a record
@login_required(login_url='my-login')
def create_record(request):
    form = AddRecordForm
    
    if request.method == 'POST':
        form = AddRecordForm(request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'Your record was created!')
            
            return redirect('dashboard')
        
    context = {'form': form}
    
    return render(request, 'crm/create-record.html', context=context)
  

# Update a record
@login_required(login_url='my-login')
def update_record(request, pk):
    
    record = ClientRecord.objects.get(id=pk)
    
    form  = UpdateRecordForm(instance=record) # Get a perticular user record by instance
    
    if request.method == 'POST':
        
        form = UpdateRecordForm(request.POST, instance=record)
        
        if form.is_valid():
            form.save()
            messages.success(request, 'Your record was updated!')
            return redirect('dashboard')
    
    context = {'form': form}
    return render(request, 'crm/update-record.html', context=context)
        
# Read or view a singular record
@login_required(login_url='my-login')
def single_record(request, pk):
    all_records = ClientRecord.objects.get(id=pk)
    
    return render(request, 'crm/view-record.html', {'record':all_records}) # without context


# Delete a Record
@login_required(login_url='my-login')
def delete_record(request, pk):
    record = ClientRecord.objects.get(id=pk)
    record.delete()
    messages.success(request, 'Your record was deleted!')
    return redirect('dashboard')

NxtLvl/crm/templates/crm/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>NxtLvl</title>

    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/cerulean/bootstrap.min.css" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <!-- Create a Navbar -->

    {% include 'crm/navbar.html' %}



    <div class="container">
        <br>
        <!--Notification Messages-->
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <p id="msg-timer" class="alert alert-success float-center text-center message_text">
                    <i class="fa fa-check" aria-hidden="true"></i> &nbsp; {{message}}

                </p>
            {% endif %}
        {% endfor %}

        {% block content %} {% endblock %}
    </div>

    <script src="{% static 'js/app.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

NxtLvl/crm/templates/crm/create-record.html
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<body>

    <div class="container bg-light shadow-md p-5 form-layout">

        <h3> Create Record </h3>

        <h6> Start adding in the required details for your client record</h6>

        <hr>
        <br>

        <form method="POST" autocomplete="off">

            {% csrf_token %}

            {{form|crispy}}

            <br>

            <button type="submit" class="btn btn-primary "> Create Record &nbsp; <i class="fa fa-check-circle" aria-hidden="true"></i></button>
            &nbsp;  &nbsp;
            <a href="{% url 'dashboard' %}" class="btn btn-secondary">Return &nbsp; <i class="fa fa-arrow-circle-left" aria-hidden="true"></i></a>


        </form>
    </div>
</body>

{% endblock %}

NxtLvl/crm/templates/crm/dashboard.html
{% extends 'crm/base.html' %}

{% block content %}

    <h4>Welcome to the Dashboard Page, {{user}}! 👋 </h4>

    <hr>

    <a class="btn btn-outline-primary btn-sm" href="{% url 'create-record' %}">
        Create a new record &nbsp; <i class="fa fa-plus-square" aria-hidden="true"></i>
    </a>
    
    <hr>

    <table class="table table-hover table-bordered">
        <thead class="table-light">
            <tr>

                <th scope="col"> ID </th>
                <th scope="col"> Full Name </th>
                <th scope="col"> Email </th>
                <th scope="col"> Phone </th>
                <th scope="col"> Address </th>
                <th scope="col"> City </th>
                <th scope="col"> Country </th>
                <th scope="col"> Company Name </th>
                <th scope="col"> Work Requirements</th>
                <th scope="col"> Amount </th>
                <th scope="col"> Start Date </th>
                <th scope="col"> Current Status </th>
                <th scope="col"> Progress Percentage </th>
                <th scope="col"> Delivery Date </th>
                <th scope="col"> Date Joined </th>

                <th scope="col"> View </th>

            </tr>

        </thead>

        <tbody>

            {% if records %}

            {% for record in records %}

            <tr>

                <td>{{record.id}}</td>
                <td>{{record.first_name}} {{record.last_name}}</td>
                <td>{{record.email}}</td>
                <td>{{record.phone}}</td>
                <td>{{record.address}}</td>
                <td>{{record.city}}</td>
                <td>{{record.country}}</td>
                <td>{{record.company_name}}</td>
                <td>{{record.work_info}}</td>
                <td>{{record.deal_amount}}</td>
                <td>{{record.start_date}}</td>
                <td>{{record.get_current_status_display}}</td>
                <td>{{record.progress_percentage}}</td>
                <td>{{record.delivery_date}}</td>
                <td>{{record.creation_date}}</td>

                <td><a class="btn btn-success btn-sm" href="{% url 'record' record.id %}"><i class="fa fa-eye" aria-hidden="true"></i></a></td>


            </tr>

            {% endfor %}

            {% endif %}

        </tbody>

    </table>


    
    




{% endblock %}

NxtLvl/crm/templates/crm/index.html
{% extends 'crm/base.html' %}

{% block content %}
    <body>
        <br>
        <br>
        <div class="text-center">
            <h3>NxtLvl...Effortless Power for Peak Customer Management</h3>
            <br>
            <h5>Keep track of your records effectively!</h5>
            <hr>
            <br>
            <a  class="btn btn-primary" type="button" href="{% url 'register' %}"> Create your account &nbsp; <i class="fa fa-user-plus" aria-hidden="true"></i></a>

        </div>


    </body>


{% endblock %}

NxtLvl/crm/templates/crm/my-login.html
{% extends 'crm/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<body>

    <div class="container bg-light shadow-md p-5 form-layout">

        <h3> Login to your account </h3>

        <hr>
        <br>

        <form method="POST" autocomplete="off">

            {% csrf_token %}

            <!-- {{login_form.username|as_crispy_field}}

            <br>

            {{login_form.password|as_crispy_field}} -->
            {{login_form|crispy}}

            <br>

            <button type="submit" class="btn btn-primary w-100 btn-block p-2"> Login &nbsp; <i class="fa fa-key" aria-hidden="true"></i> </button>


        </form>

        <br>

        <div class="text-center">

            <p> Don't have an account? </p> <a href="{% url 'register' %}"> Register </a>

        </div>


    </div>

    <br>

</body>


{% endblock %}

NxtLvl/crm/templates/crm/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary justify-content-center">

    <a class="navbar-brand main-heading" href="{% url '' %}"> 
            
      &nbsp; NxtLvl
    
    </a>
  
  
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
  
    </button>
  
  
      <div class="collapse navbar-collapse text-center" id="navbarNavDropdown">
  
        
        <ul class="navbar-nav mr-auto">
  
  
          &nbsp;     &nbsp;     &nbsp; 
  
          {% if user.is_authenticated %}
  
            <li class="nav-item">
        
              <a class="nav-link" href="{% url 'dashboard' %}">Dashboard &nbsp; <i class="fa fa-home" aria-hidden="true"></i> </a>
  
            </li>
  
  
            &nbsp;     &nbsp;     &nbsp; 
  
  
            <li class="nav-item">
  
              <a class="nav-link" href="{% url 'user-logout' %}">Sign out &nbsp; <i class="fa fa-sign-out" aria-hidden="true"></i> </a>
  
            </li>
  
  
        </ul>
  
        {% else %}
  
        <li class="nav-item">
  
          <a class="nav-link" href="{% url 'register' %}"> Register </a>
  
        </li>
  
  
        &nbsp;     &nbsp;     &nbsp; 
  
  
        <li class="nav-item">
  
          <a class="nav-link" href="{% url 'my-login' %}">Login</a>
  
        </li>
  
  
        {% endif %}
      
        
      </div>
  
  
  </nav>

NxtLvl/crm/templates/crm/register.html
{% extends 'crm/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<body>



    <div class="container bg-light shadow-md p-5 form-layout">

        <h3> Create your account</h3>
        <h5> Start managing your clients today!</h5>
        <hr>
        <br>
        <form method="POST" autocomplete="off">
            {% csrf_token %}

            {{form|crispy}}

            <br>

            <button type="submit" class="btn btn-primary w-100 btn-block p2">Create account &nbsp; <i class="fa fa-user" aria-hidden="true"></i></button>

        </form>
        <br>
        <div class="text-center">
            <p>Already have an account?</p> <a href="{% url 'my-login' %}">Login</a>
        </div>
        <br>

    </div>
    
</body>
{% endblock %}

NxtLvl/crm/templates/crm/update-record.html
{% extends 'crm/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<body>

    <div class="container bg-light shadow-md p-5 form-layout">

        <h3> Update Record </h3>

        <h6> Update your record down below</h6>

        <hr>
        <br>

        <form method="POST" autocomplete="off">

            {% csrf_token %}

            {{form|crispy}}

            <br>

            <button type="submit" class="btn btn-primary "> Update record &nbsp; <i class="fa fa-plus-square" aria-hidden="true"></i></button>
            &nbsp; &nbsp;
            <a href="{% url 'dashboard' %}" class="btn btn-secondary">Return &nbsp; <i class="fa fa-arrow-circle-left" aria-hidden="true"></i></a>


        </form>
    </div>
    <br>
</body>

{% endblock %}

NxtLvl/crm/templates/crm/view-record.html
{% extends 'crm/base.html' %}

{% block content %}

    <div class="card text-center">

        <div class="card-body">
            <i class="fa fa-user-circle-o" aria-hidden="true"></i> &nbsp;

            <strong>
          
                &nbsp;  &nbsp;
    
                {{record.first_name|upper}}
                {{record.last_name}}
    
            </strong>
            <hr>

            <p><strong>ID: </strong>{{record.id}}</p> 
            <p><strong>Email: </strong>{{record.email}}</p>
            <p><strong>Phone Number: </strong>{{record.phone}}</p>
            <p><strong>Address: </strong>{{record.address}}</p>
            <p><strong>City: </strong>{{record.city}}</p>
            <p><strong>Country: </strong>{{record.country}}</p>
            <p><strong>Company Name: </strong>{{record.company_name}}</p>
            <p><strong>Work Requirements: </strong>{{record.work_info}}</p>
            <p><strong>Amount: </strong>{{record.deal_amount}}</p>
            <p><strong>Start Date: </strong>{{record.start_date}}</p>
            <p><strong>Current Status: </strong>{{record.get_current_status_display}}</p>
            <p><strong>Progress Percentege: </strong>{{record.progress_percentage}}</p>
            <p><strong>Delivery Date: </strong>{{record.delivery_date}}</p>
            <p><strong>Date Joined: </strong>{{record.creation_date}}</p>
           

        </div>

    </div>

    <br>
    <a href="{% url 'dashboard' %}" class="btn btn-secondary">Return to Dashboard &nbsp; <i class="fa fa-arrow-left" aria-hidden="true"></i></a>
    &nbsp;
    <a href="{% url 'update-record' record.id %}" class="btn btn-info">Update Record &nbsp; <i class="fa fa-plus-square" aria-hidden="true"></i> </a>
    &nbsp;
    <a href="{% url 'delete-record' record.id %}" class="btn btn-danger">Delete Record &nbsp; <i class="fa fa-minus-square" aria-hidden="true"></i></a>
    &nbsp;

{% endblock %}